# Generated by Django 6.0.2 on 2026-02-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep_name', models.CharField(max_length=70)),
                ('Dep_desc', models.CharField(max_length=100)),
                ('Dep_head', models.CharField(max_length=70)),
            ],
        ),
    ]
