# Generated by Django 6.0.2 on 2026-02-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Image', models.ImageField(upload_to='image')),
                ('Code', models.CharField(max_length=20)),
                ('Dept', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
