# Generated by Django 6.0.2 on 2026-02-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_query_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Status',
            field=models.CharField(default='pending'),
        ),
    ]
