# Generated by Django 6.0.2 on 2026-03-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Item_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
